services:
  - type: web
    name: scorable-collecteur
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: GH_TOKEN
        sync: false
      - key: GH_REPO
        value: "Donkey07Kong/scorable-collecteur"
      - key: GH_DATA_PATH
        value: "data"
