services:
  - type: web
    name: scorable-collecteur
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    healthCheckPath: /
    autoDeploy: false
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
